//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password is not allowed for this user..
        /// </summary>
        public static string ChangePasswordNotAllowed {
            get {
                return ResourceManager.GetString("ChangePasswordNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger point type does not exist.
        /// </summary>
        public static string ChargerPointTypeMustExist {
            get {
                return ResourceManager.GetString("ChargerPointTypeMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already used.
        /// </summary>
        public static string EmailMustBeUnique {
            get {
                return ResourceManager.GetString("EmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time must be less than To Time.
        /// </summary>
        public static string FromTimeToTimeRange {
            get {
                return ResourceManager.GetString("FromTimeToTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected identifier doesn&apos;t exist.
        /// </summary>
        public static string IdentifierDoesntExist {
            get {
                return ResourceManager.GetString("IdentifierDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is invalid.
        /// </summary>
        public static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request details.
        /// </summary>
        public static string InvalidRequestDetails {
            get {
                return ResourceManager.GetString("InvalidRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected map services are invalid.
        /// </summary>
        public static string InvalidSelctedMapServices {
            get {
                return ResourceManager.GetString("InvalidSelctedMapServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected privileges are invalid.
        /// </summary>
        public static string InvalidSelctedPrivileges {
            get {
                return ResourceManager.GetString("InvalidSelctedPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location feature doesn&apos;t exist.
        /// </summary>
        public static string LocationDoesntExist {
            get {
                return ResourceManager.GetString("LocationDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Is Required.
        /// </summary>
        public static string LocationIsRequired {
            get {
                return ResourceManager.GetString("LocationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another record is using the same name.
        /// </summary>
        public static string NameMustBeUnique {
            get {
                return ResourceManager.GetString("NameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is already used within the same hierarchy.
        /// </summary>
        public static string NameMustBeUniqueWithinUnit {
            get {
                return ResourceManager.GetString("NameMustBeUniqueWithinUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is not valid.
        /// </summary>
        public static string NotValidUrl {
            get {
                return ResourceManager.GetString("NotValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization unit or its sub units are currently linked to none deleted users.
        /// </summary>
        public static string OrganizationUnitIsLinkedToUsers {
            get {
                return ResourceManager.GetString("OrganizationUnitIsLinkedToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected organization unit doesnot exist in the database.
        /// </summary>
        public static string OrganizationUnitMustExist {
            get {
                return ResourceManager.GetString("OrganizationUnitMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parent is not valid for this record.
        /// </summary>
        public static string ParentLocationNotValid {
            get {
                return ResourceManager.GetString("ParentLocationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linking between the unit and the parent unit is invalid.
        /// </summary>
        public static string ParentUnitChildUnitLinkingIsInvalid {
            get {
                return ResourceManager.GetString("ParentUnitChildUnitLinkingIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role is currently linked to none deleted users.
        /// </summary>
        public static string RoleIsLinkedToUsers {
            get {
                return ResourceManager.GetString("RoleIsLinkedToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected role doesnot exist in the database.
        /// </summary>
        public static string RoleMustExist {
            get {
                return ResourceManager.GetString("RoleMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thes selected status doesnot exist .
        /// </summary>
        public static string StatusMustExist {
            get {
                return ResourceManager.GetString("StatusMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already rated this charging point .
        /// </summary>
        public static string UserAlreadyRated {
            get {
                return ResourceManager.GetString("UserAlreadyRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is already used.
        /// </summary>
        public static string UserNameMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameMustBeUnique", resourceCulture);
            }
        }
    }
}
