// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class AttachmentChargerPointConfiguration : IEntityTypeConfiguration<AttachmentChargerPoint>
{
    public void Configure(EntityTypeBuilder<AttachmentChargerPoint> entity)
    {
        entity.ToTable("AttachmentChargerPoint");

        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.FileType).HasMaxLength(50);
        entity.Property(e => e.ModifiedAt).HasColumnType("datetime");

        entity.HasOne(d => d.ChargingPoint).WithMany(p => p.AttachmentChargerPoints)
            .HasForeignKey(d => d.ChargingPointId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_AttachmentChargerPoint_ChargingPoint");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<AttachmentChargerPoint> entity);
}