// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;
using Infrastructrue.UploadFiles;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class ChargingPlugConfiguration : IEntityTypeConfiguration<ChargingPlug>
{
    
    public void Configure(EntityTypeBuilder<ChargingPlug> entity)
    {
        entity.ToTable("ChargingPlug");

        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.ModifiedAt).HasColumnType("datetime");

        entity.HasOne(d => d.ChargingPoint).WithMany(p => p.ChargingPlugs)
            .HasForeignKey(d => d.ChargingPointId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPlug_ChargingPoint");

        entity.HasOne(d => d.PlugType).WithMany(p => p.ChargingPlugs)
            .HasForeignKey(d => d.PlugTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPlug_PlugType");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ChargingPlug> entity);
}