// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class ChargingPointAttachmentConfiguration : IEntityTypeConfiguration<ChargingPointAttachment>
{
    public void Configure(EntityTypeBuilder<ChargingPointAttachment> builder)
    {
        builder.ToTable("ChargingPointAttachment");

        builder.Property(e => e.CreatedAt).HasColumnType("datetime");
        builder.Property(e => e.FileExtension).HasMaxLength(50);
        builder.Property(e => e.ModifiedAt).HasColumnType("datetime");

        builder.Property(x => x.ContentType).HasMaxLength(50);
        builder.Property(x => x.FileName).HasMaxLength(255);
        
        
        builder.HasOne(d => d.ChargingPoint).WithMany(p => p.ChargingPointAttachments)
            .HasForeignKey(d => d.ChargingPointId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_AttachmentChargerPoint_ChargingPoint");

        OnConfigurePartial(builder);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ChargingPointAttachment> entity);
}