// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class ChargingPointConfiguration : IEntityTypeConfiguration<ChargingPoint>
{
    public void Configure(EntityTypeBuilder<ChargingPoint> builder)
    {
        builder.ToTable("ChargingPoint");

        builder.Property(e => e.CityName).HasMaxLength(500);
        builder.Property(e => e.CountryName).HasMaxLength(500);
        builder.Property(e => e.CreatedAt).HasColumnType("datetime");
        builder.Property(e => e.FromTime).HasMaxLength(8);
        builder.Property(e => e.MethodPayment).HasMaxLength(20);
        builder.Property(e => e.Name).HasMaxLength(255);
        builder.Property(e => e.Address).HasMaxLength(500);
        builder.Property(e => e.Note).HasMaxLength(500);
        builder.Property(e => e.Phone).HasMaxLength(20);
        builder.Property(e => e.OwnerPhone).HasMaxLength(20);
        builder.Property(e => e.Price).HasColumnName("price");
        builder.Property(e => e.ToTime).HasMaxLength(8);
        

        builder.HasOne(d => d.ChargerPointType).WithMany(p => p.ChargingPoints)
            .HasForeignKey(d => d.ChargerPointTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPoint_ChargingPointType");

        builder.HasOne(d => d.Owner).WithMany(p => p.ChargingPoints)
            .HasForeignKey(d => d.OwnerId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPoint_UserAccount");

        builder.HasOne(d => d.Status).WithMany(p => p.ChargingPoints)
            .HasForeignKey(d => d.StatusId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPoint_Status");

        builder.HasOne(d => d.StationType).WithMany(p => p.ChargingPoints)
            .HasForeignKey(d => d.StationTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("ChargingPoint_StationType_Id_fk");

        // Loyalty Blocking
        builder.Property(e => e.IsLoyaltyBlocked)
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(e => e.LoyaltyBlockedAt)
            .HasColumnType("datetime");

        builder.Property(e => e.LoyaltyBlockedUntil)
            .HasColumnType("datetime");

        builder.Property(e => e.LoyaltyBlockReason)
            .HasMaxLength(500);

        builder.HasOne(d => d.LoyaltyBlockedByUser)
            .WithMany()
            .HasForeignKey(d => d.LoyaltyBlockedByUserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ChargingPoint_LoyaltyBlockedByUser");

        // Loyalty Credit Limit
        builder.Property(e => e.LoyaltyCreditLimit)
            .HasColumnType("decimal(18,3)");

        builder.Property(e => e.LoyaltyCurrentBalance)
            .IsRequired()
            .HasDefaultValue(0m)
            .HasColumnType("decimal(18,3)");

        OnConfigurePartial(builder);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ChargingPoint> entity);
}