// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;

#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class ChargingPointTypeConfiguration : IEntityTypeConfiguration<ChargingPointType>
{
    public void Configure(EntityTypeBuilder<ChargingPointType> entity)
    {
        entity.ToTable("ChargingPointType");

        entity.Property(e => e.Name).HasMaxLength(50);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ChargingPointType> entity);
}