// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class NotificationInboxConfiguration : IEntityTypeConfiguration<NotificationInbox>
{
    public void Configure(EntityTypeBuilder<NotificationInbox> entity)
    {
        entity.ToTable("NotificationInbox");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(256);

        entity.Property(e => e.Body)
            .IsRequired()
            .HasMaxLength(1000);

        entity.Property(e => e.DeepLink)
            .HasMaxLength(500);

        entity.Property(e => e.Data);

        entity.Property(e => e.IsRead)
            .IsRequired();

        entity.Property(e => e.CreatedAt)
            .HasColumnType("datetime");

        entity.Property(e => e.ModifiedAt)
            .HasColumnType("datetime");

        entity.HasOne(d => d.User)
            .WithMany(p => p.NotificationInboxes)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NotificationInbox_UserAccount");

        entity.HasOne(d => d.NotificationType)
            .WithMany(p => p.NotificationInboxes)
            .HasForeignKey(d => d.NotificationTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_NotificationInbox_NotificationType");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<NotificationInbox> entity);
}
