// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;

#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class PlugTypeConfiguration : IEntityTypeConfiguration<PlugType>
{
    public void Configure(EntityTypeBuilder<PlugType> entity)
    {
        entity.ToTable("PlugType");

        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.ModifiedAt).HasColumnType("datetime");
        entity.Property(e => e.Name).HasMaxLength(50);
        entity.Property(e => e.SerialNumber).HasMaxLength(255);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<PlugType> entity);
}