// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class RolePrivlageConfiguration : IEntityTypeConfiguration<RolePrivlage>
{
    public void Configure(EntityTypeBuilder<RolePrivlage> entity)
    {
        entity.ToTable("RolePrivlage");

        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.PrivilegeId).HasColumnName("PivlageID");
        entity.Property(e => e.RoleId).HasColumnName("RoleID");

        entity.HasOne(d => d.Pivlage).WithMany(p => p.RolePrivlages)
            .HasForeignKey(d => d.PrivilegeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RolePrivlage_Privalge");

        entity.HasOne(d => d.Role).WithMany(p => p.RolePrivlages)
            .HasForeignKey(d => d.RoleId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RolePrivlage_ApplicationRole");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<RolePrivlage> entity);
}