// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Domain.Enitites;


#nullable disable

namespace Infrastructrue.Persistence.Configurations;

public partial class UserComplaintConfiguration : IEntityTypeConfiguration<UserComplaint>
{
    public void Configure(EntityTypeBuilder<UserComplaint> entity)
    {
        entity.HasKey(e => e.Id).HasName("PK_NewTable");

        entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        entity.Property(e => e.ModifiedAt).HasColumnType("datetime");
        entity.Property(e => e.Note).HasMaxLength(500);

        entity.HasOne(d => d.ChargingPoint).WithMany(p => p.UserComplaints)
            .HasForeignKey(d => d.ChargingPointId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserComplaints_ChargingPoint");

        entity.HasOne(d => d.User).WithMany(p => p.UserComplaints)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserComplaints_UserAccount");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<UserComplaint> entity);
}