namespace Application.ServiceProviders.Queries.GetAllServiceProviders;

public record ServiceProviderDto(
    int Id,
    string Name,
    int OwnerId,
    string? OwnerName,
    int ServiceCategoryId,
    string? ServiceCategoryName,
    string? ServiceCategoryNameAr,
    int StatusId,
    string? StatusName,
    string? Description,
    string? Phone,
    string? Address,
    string? CountryName,
    string? CityName,
    double Latitude,
    double Longitude,
    double? Price,
    string? PriceDescription,
    string? FromTime,
    string? ToTime,
    string? MethodPayment,
    int VisitorsCount,
    bool IsVerified,
    bool HasOffer,
    string? OfferDescription,
    string? Service,
    string? Icon,
    string? WhatsAppNumber,
    string? WebsiteUrl,
    double AvgRating,
    int RateCount,
    List<string> Images,
    DateTime CreatedAt,
    bool IsPartner
);
