// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Domain.Common;

namespace Domain.Enitites;

public partial class AttachmentChargerPoint :BaseAuditableEntity
{
    public int ChargingPointId { get; set; }

    public int FilePath { get; set; }

    public int FileSize { get; set; }
    public string FileType { get; set; } = null!;
    
    public virtual ChargingPoint ChargingPoint { get; set; } = null!;
}