// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Domain.Common;

namespace Domain.Enitites;

public partial class ChargingPointAttachment :BaseAuditableEntity
{
    public int ChargingPointId { get; set; }

    public long FileSize { get; set; }
    
    public string FileExtension { get; set; } = null!;
    
    public string FileName { get; set; } = null!;

    public string ContentType { get; set; } = null!;
    public virtual ChargingPoint ChargingPoint { get; set; } = null!;
}