// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Domain.Common;

namespace Domain.Enitites;

public partial class ChargingPlug:BaseAuditableEntity
{
    public int ChargingPointId { get; set; }
    public int PlugTypeId { get; set; }
    public virtual ChargingPoint ChargingPoint { get; set; } = null!;
    public virtual PlugType PlugType { get; set; } = null!;
}