// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Enitites;

public partial class Privilege
{
    public int Id { get; set; }

    public string Description { get; set; } = null!;

    public string Code { get; set; } = null!;

    public virtual ICollection<RolePrivlage> RolePrivlages { get; set; } = new List<RolePrivlage>();
}