// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Domain.Common;

namespace Domain.Enitites;

public partial class RolePrivlage:BaseAuditableEntity
{
    public int RoleId { get; set; }
    public int PrivilegeId { get; set; }
    
    public virtual Privilege Pivlage { get; set; } = null!;

    public virtual Role Role { get; set; } = null!;
}