// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Domain.Common;

namespace Domain.Enitites;

public partial class Role:BaseAuditableEntity
{
    public string Name { get; set; } = null!;
    public virtual ICollection<RolePrivlage> RolePrivlages { get; set; } = new List<RolePrivlage>();

    public virtual ICollection<UserAccount> UserAccounts { get; set; } = new List<UserAccount>();
}